### ISSUE TITLE
illegal padding

### ISSUE THREAD

**Issue by phoebusb** [swisscom/ruby-netsnmp#47] opened 2021-05-18 09:00 UTC
Hi Thiago,

We are currently using version 0.4.0 (previously 0.1.7, has the same problem) and are experiencing an error.

On a Huawei Aggregator we get an illegal padding error when trying to decode the response:

```
_irb(main):230:0> begin
irb(main):231:1> d.get_snmp(**".1.3.6.1.4.1.2011.5.14.6.4.1.4.234881152"**)
irb(main):232:1> rescue StandardError => e
irb(main):233:1> puts e.message
irb(main):234:1> puts e.backtrace
irb(main):235:1> end
_**--> pdu_der:**_ 
**"0;\x04\f\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01\x04\x00\xA2)\x02\x04A0\xAEQ\x02\x01\x00\x02\x01\x000\e0\x19\x06\x11+\x06\x01\x04\x01\x8F[\x05\x0E\x06\x04\x01\x04\xF0\x80\x81\x00\x02\x04\xFF\xA5\xC8?"**
**illegal padding**
(irb):101:in `decode'
(irb):101:in `decode'
/usr/local/bundle/gems/netsnmp-0.4.0/lib/netsnmp/message.rb:61:in `decode'
/usr/local/bundle/gems/netsnmp-0.4.0/lib/netsnmp/v3_session.rb:88:in `decode'
/usr/local/bundle/gems/netsnmp-0.4.0/lib/netsnmp/v3_session.rb:27:in `send'
/usr/local/bundle/gems/netsnmp-0.4.0/lib/netsnmp/client.rb:55:in `block in get'
/usr/local/bundle/gems/netsnmp-0.4.0/lib/netsnmp/client.rb:155:in `handle_retries'
/usr/local/bundle/gems/netsnmp-0.4.0/lib/netsnmp/client.rb:55:in `get'
/usr/src/app/lib/device/generic_snmp.rb:86:in `get_snmp'_
```

If we do the same via snmpget cli we obtain the correct result:

```
_snmpget -v 3 -n '' -u 'bla' -a MD5 -A 'bla' -x DES -X 'bla' -l authPriv 10.80.4.103 .1.3.6.1.4.1.2011.5.14.6.4.1.4.234881152
**iso.3.6.1.4.1.2011.5.14.6.4.1.4.234881152 = INTEGER: -5910819_**
```

As highlighted, the pdu_der that OpenSSL::ASN1_decode tries to decode is as follows (output from a puts):
**"0;\x04\f\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01\x04\x00\xA2)\x02\x04A0\xAEQ\x02\x01\x00\x02\x01\x000\e0\x19\x06\x11+\x06\x01\x04\x01\x8F[\x05\x0E\x06\x04\x01\x04\xF0\x80\x81\x00\x02\x04\xFF\xA5\xC8?"**

Any idea, what's wrong with the pdu_der?

cheers
David

**Comment by HoneyryderChuck** [comment] 2021-05-18 17:50
Hi David. It's Tiago (without the "h") :) 

Can you run your script with [debug log turned on](https://github.com/swisscom/ruby-netsnmp#debugging) and paste the output here?

**Comment by phoebusb** [comment] 2021-05-18 19:02
Hi Tiago,
Must be because of Thiago Silva :-)
OK, I'll do it tomorrow and let you know the result.

regards
David

**Comment by phoebusb** [comment] 2021-05-19 07:27
Oi Tiago,

Here's the output:

irb(main):004:0> d.get_snmp(".1.3.6.1.4.1.2011.5.14.6.4.1.4.234881152")

sending probe...

pdu: 3014
        engine_id: 0400 ("")
        context: 0400 ("")
        request: a00e
                request_id: 0204 072e 394c ("120469836")
                error: 0201 ("0")
                error_index: 0201 ("0")
                varbinds: 3000

encoding PDU in V3 message...

security_params: 3028
        engine_id: 0400 ("")
        engine_boots: 0201 ("0")
        engine_time: 0201 ("0")
        username: 040e 4745 542d 5633 2d4e 4f43 5553 4552 ("XXX-XX-XXXXXXX")
        auth_mask: 040c 0000 0000 0000 0000 0000 0000 ("\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000")
        OctetString: 0400 ("")

v3_message: 3058
        message_version: 0201 ("3")
        headers: 3011
                message_id: 0204 5016 5363 ("1343640419")
                max_message_size: 0203 00ff ("65507")
                message_flags: 0401 ("\x04")
                security_model: 0201 ("3")
        security_params: 042a 3028 0400 0201 0002 0100 040e 4745 542d 5633 2d4e 4f43 5553 4552 040c 0000 0000 0000 0000 0000 0000 0400 ("0(\x04\x00\x02\x01\x00\x02\x01\x00\x04\x0EXXX-XX-XXXXXXX\x04\f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00")
        pdu: 3014
                engine_id: 0400 ("")
                context: 0400 ("")
                request: a00e
                        request_id: 0204 072e 394c ("120469836")
                        error: 0201 ("0")
                        error_index: 0201 ("0")
                        varbinds: 3000

3058 0201 0330 1102 0450 1653 6302 0300
ffe3 0401 0402 0103 042a 3028 0400 0201
0002 0100 040e 4745 542d 5633 2d4e 4f43
5553 4552 040c 0000 0000 0000 0000 0000
0000 0400 3014 0400 0400 a00e 0204 072e
394c 0201 0002 0100 3000

received encoded V3 message

3079 0201 0330 1002 0450 1653 6302 023a
9804 0100 0201 0304 3c30 3a04 0c80 0007
db03 04f9 38d5 07fc 0102 0422 cc13 1002
0400 d87e f704 0e47 4554 2d56 332d 4e4f
4355 5345 5204 0c00 0000 0000 0000 0000
0000 0004 0030 2404 0004 00a8 1e02 0100
0201 0002 0100 3013 3011 060a 2b06 0106
030f 0101 0400 4103 0761

v3_message: 3079
        message_version: 0201 ("3")
        headers: 3010
                Integer: 0204 5016 5363 ("1343640419")
                Integer: 0202 3a98 ("15000")
                message_flags: 0401 ("\x00")
                Integer: 0201 ("3")
        security_params: 043c 303a 040c 8000 07db 0304 f938 d507 fc01 0204 22cc 1310 0204 00d8 7ef7 040e 4745 542d 5633 2d4e 4f43 5553 4552 040c 0000 0000 0000 0000 0000 0000 0400 ("0:\x04\f\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01\x02\x04\"\xCC\x13\x10\x02\x04\x00\xD8~\xF7\x04\x0EXXX-XX-XXXXXXX\x04\f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00")
        pdu: 3024
                OctetString: 0400 ("")
                OctetString: 0400 ("")
                ASN1Data: a81e
                        Integer: 0201 ("0")
                        Integer: 0201 ("0")
                        Integer: 0201 ("0")
                        Sequence: 3013
                                Sequence: 3011
                                        ObjectId: 060a 2b06 0106 030f 0101 0400 ("1.3.6.1.6.3.15.1.1.4.0")
                                        ASN1Data: 4103 0761

security_params: 303a
        engine_id: 040c 8000 07db 0304 f938 d507 fc01 ("\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01")
        engine_boots: 0204 22cc 1310 ("583799568")
        engine_time: 0204 00d8 7ef7 ("14188279")
        username: 040e 4745 542d 5633 2d4e 4f43 5553 4552 ("XXX-XX-XXXXXXX")
        auth_param: 040c 0000 0000 0000 0000 0000 0000 ("\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00")
        priv_param: 0400 ("")

received response PDU

pdu: 3024
        engine_id: 0400 ("")
        context: 0400 ("")
        request: a81e
                request_id: 0201 ("0")
                error: 0201 ("0")
                error_index: 0201 ("0")
                varbinds: 3013
                        Sequence: 3011
                                ObjectId: 060a 2b06 0106 030f 0101 0400 ("1.3.6.1.6.3.15.1.1.4.0")
                                Integer: 0203 0761 ("483675")

sending request...

pdu: 3037
        engine_id: 040c 8000 07db 0304 f938 d507 fc01 ("\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01")
        context: 0400 ("")
        request: a025
                request_id: 0204 3a4c c67b ("978110075")
                error: 0201 ("0")
                error_index: 0201 ("0")
                varbinds: 3017
                        Sequence: 3015
                                ObjectId: 0611 2b06 0104 018f 5b05 0e06 0401 04f0 8081 ("1.3.6.1.4.1.2011.5.14.6.4.1.4.234881152")
                                Null: 0500

encoding PDU in V3 message...

security_params: 3042
        engine_id: 040c 8000 07db 0304 f938 d507 fc01 ("\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01")
        engine_boots: 0204 22cc 1310 ("583799568")
        engine_time: 0204 00d8 7ef7 ("14188279")
        username: 040e 4745 542d 5633 2d4e 4f43 5553 4552 ("XXX-XX-XXXXXXXR")
        auth_mask: 040c 0000 0000 0000 0000 0000 0000 ("\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000")
        salt: 0408 22cc 1310 0000 0000 ("\"\xCC\x13\x10\x00\x00\x00\x00")

v3_message: 3081
        message_version: 0201 ("3")
        headers: 3011
                message_id: 0204 1a96 c2c4 ("446087876")
                max_message_size: 0203 00ff ("65507")
                message_flags: 0401 ("\a")
                security_model: 0201 ("3")
        security_params: 0444 3042 040c 8000 07db 0304 f938 d507 fc01 0204 22cc 1310 0204 00d8 7ef7 040e 4745 542d 5633 2d4e 4f43 5553 4552 040c 0000 0000 0000 0000 0000 0000 0408 22cc 1310 0000 0000 ("0B\x04\f\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01\x02\x04\"\xCC\x13\x10\x02\x04\x00\xD8~\xF7\x04\x0EXXX-XX-XXXXXXX\x04\f\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\b\"\xCC\x13\x10\x00\x00\x00\x00")
        encrypted_pdu: 0448 ac28 c552 f1e7 4109 e627 9e64 fe72 e344 86e9 1ca3 3ed0 195a 9eff d35b afe8 d0f3 42cd 09bb 2e62 308c 9f4b a79a 9709 ae57 f590 2462 5ee2 45f7 3b5c dba8 1798 6559 59cc 8f84 ad6f 383e ("\xAC(\xC5R\xF1\xE7A\t\xE6'\x9Ed\xFEr\xE3D\x86\xE9\x1C\xA3>\xD0\x19Z\x9E\xFF\xD3[\xAF\xE8\xD0\xF3B\xCD\t\xBB.b0\x8C\x9FK\xA7\x9A\x97\t\xAEW\xF5\x90$b^\xE2E\xF7;\\\xDB\xA8\x17\x98eYY\xCC\x8F\x84\xADo8>")

3081 a602 0103 3011 0204 1a96 c2c4 0203
00ff e304 0107 0201 0304 4430 4204 0c80
0007 db03 04f9 38d5 07fc 0102 0422 cc13
1002 0400 d87e f704 0e47 4554 2d56 332d
4e4f 4355 5345 5204 0c00 0000 0000 0000
0000 0000 0004 0822 cc13 1000 0000 0004
48ac 28c5 52f1 e741 09e6 279e 64fe 72e3
4486 e91c a33e d019 5a9e ffd3 5baf e8d0
f342 cd09 bb2e 6230 8c9f 4ba7 9a97 09ae
57f5 9024 625e e245 f73b 5cdb a817 9865
5959 cc8f 84ad 6f38

signing V3 message...

auth: 040c 9f36 8e36 52ad 6bde 4978 6b27 ("\x9F6\x8E6R\xADk\xDEIxk'")

3081 a602 0103 3011 0204 1a96 c2c4 0203
00ff e304 0107 0201 0304 4430 4204 0c80
0007 db03 04f9 38d5 07fc 0102 0422 cc13
1002 0400 d87e f704 0e47 4554 2d56 332d
4e4f 4355 5345 5204 0c9f 368e 3652 ad6b
de49 786b 2704 0822 cc13 1000 0000 0004
48ac 28c5 52f1 e741 09e6 279e 64fe 72e3
4486 e91c a33e d019 5a9e ffd3 5baf e8d0
f342 cd09 bb2e 6230 8c9f 4ba7 9a97 09ae
57f5 9024 625e e245 f73b 5cdb a817 9865
5959 cc8f 84ad 6f38

received encoded V3 message

3082 009d 0201 0330 1002 041a 96c2 c402
023a 9804 0103 0201 0304 4430 4204 0c80
0007 db03 04f9 38d5 07fc 0102 0422 cc13
1002 0400 d87e f704 0e47 4554 2d56 332d
4e4f 4355 5345 5204 0cc4 ff78 ad3e 8270
a176 9415 0204 0800 0013 1000 00ac d404
4076 2560 9574 4329 ce1c f078 bea1 22e4
d71b 7ca7 216d aaeb f307 dddf 3c20 8a04
7606 629b 7373 3a00 de66 ac8e 0f25 64ab
8628 b8ef 2480 e37a 95ba e737 914d 2b23

v3_message: 3081
        message_version: 0201 ("3")
        headers: 3010
                Integer: 0204 1a96 c2c4 ("446087876")
                Integer: 0202 3a98 ("15000")
                message_flags: 0401 ("\x03")
                Integer: 0201 ("3")
        security_params: 0444 3042 040c 8000 07db 0304 f938 d507 fc01 0204 22cc 1310 0204 00d8 7ef7 040e 4745 542d 5633 2d4e 4f43 5553 4552 040c c4ff 78ad 3e82 70a1 7694 1502 0408 0000 1310 0000 acd4 ("0B\x04\f\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01\x02\x04\"\xCC\x13\x10\x02\x04\x00\xD8~\xF7\x04\x0EXXX-XX-XXXXXXX\x04\f\xC4\xFFx\xAD>\x82p\xA1v\x94\x15\x02\x04\b\x00\x00\x13\x10\x00\x00\xAC\xD4")
        pdu: 0440 7625 6095 7443 29ce 1cf0 78be a122 e4d7 1b7c a721 6daa ebf3 07dd df3c 208a 0476 0662 9b73 733a 00de 66ac 8e0f 2564 ab86 28b8 ef24 80e3 7a95 bae7 3791 4d2b 2348 ("v%`\x95tC)\xCE\x1C\xF0x\xBE\xA1\"\xE4\xD7\e|\xA7!m\xAA\xEB\xF3\a\xDD\xDF< \x8A\x04v\x06b\x9Bss:\x00\xDEf\xAC\x8E\x0F%d\xAB\x86(\xB8\xEF$\x80\xE3z\x95\xBA\xE77\x91M+#H")

security_params: 3042
        engine_id: 040c 8000 07db 0304 f938 d507 fc01 ("\x80\x00\a\xDB\x03\x04\xF98\xD5\a\xFC\x01")
        engine_boots: 0204 22cc 1310 ("583799568")
        engine_time: 0204 00d8 7ef7 ("14188279")
        username: 040e 4745 542d 5633 2d4e 4f43 5553 4552 ("XXX-XX-XXXXXXX")
        auth_param: 040c c4ff 78ad 3e82 70a1 7694 1502 ("\xC4\xFFx\xAD>\x82p\xA1v\x94\x15\x02")
        priv_param: 0408 0000 1310 0000 acd4 ("\x00\x00\x13\x10\x00\x00\xAC\xD4")

message has been verified

message has been decrypted
Traceback (most recent call last):
        2: from (irb):4
        1: from lib/device/generic_snmp.rb:86:in `get_snmp'
OpenSSL::ASN1::ASN1Error (illegal padding)

**Comment by HoneyryderChuck** [comment] 2021-05-19 23:07
It seems that the issue is from openssl. According to [this bug ticket here](https://github.com/openssl/openssl/issues/4320):

* openssl has issues with negative numbers extra-padded illegally according to the supported ASN.1 RFC5280.
* OpenSSL used to tolerate this (should work with 0.9.8) but doesn't any more.

I'll close this ticket, as it's a dependency issue, and you can follow up with openssl. I don't have a great workaround to suggest here, given that I'm not expecting to change the underlying ASN.1 parser, so feel free to retry this with a ruby built against openssl 0.9.8 .

**Closed by HoneyryderChuck** 2021-05-19 23:07 UTC

**Comment by phoebusb** [comment] 2021-05-20 07:46
Hi Tiago,

Thanks a lot for your investigation! So as far as I understood the root cause seems to be the aggregator that wrongly encodes negative numbers. So until that behaviour of the aggregators changes we'll stick to the cli tool for that request.

However, I wonder if the cli tool does a sanitizing of the values since the snmpget also relies on underlying openssl ...

Again, thanks for your work!
cheers
David

**Comment by HoneyryderChuck** [comment] 2021-05-20 09:19
Hey David,

> So as far as I understood the root cause seems to be the aggregator that wrongly encodes negative numbers. 

It's not that it's "wrong", it's just that it might be respecting a different RFC version, and more forgiving parsers let it through, and `openssl`'s way stricter.

> I wonder if the cli tool does a sanitizing of the values since the snmpget also relies on underlying openssl ...

I don't think it does. AFAIK they [ship their own parser](https://github.com/net-snmp/net-snmp/blob/master/snmplib/asn1.c).

Bear in mind that `openssl`'s parser is tailored to parsing X509 certificates and **not** to the snmp case. I use it out of convenience, as ruby ships with an `openssl` binding, and it's better to use what's there than "writing my own parser" (there's a corner of the internet reserved for jokes about ASN.1 parsers, specially in the SecOps community).

Python's "snmp" uses [pyasn](https://github.com/hadiasghari/pyasn), just to give you an example of other tools and how they deal with ASN.1 parsing.

This gem could technically also go down that path, i.e. optionally "bundling" a separate parser gem, such as [rasn1](https://github.com/sdaubert/rasn1). This could also fix [other historical issues that I've had in the past](https://github.com/swisscom/ruby-netsnmp/issues/2). But I never prioritized it enough. Feel free to pick up on it if you feel you could do it. If it actually fixes your use-case, I can give you some assistance in the "start contributing" process.

**Comment by phoebusb** [comment] 2021-05-20 14:57
OK, now I fully understand! snmpget uses openssl only for the authentication/encryption but not for the asn parsing. Anyway, in that case HUA seems to be at least inconsistent, since on the mcan I can read out the same (negative) values without any problem ...

Well, I don't think I'd be able to successfully integrate a new asn1 parser, especially if I look at the source code of the snmpget package you linked above :-)

Nevertheless, thanks a lot for your extremely competent answers - I learned quite a bit about the protocol.

best wishes
David

**Comment by HoneyryderChuck** [comment] 2021-05-20 18:10
>  HUA seems to be at least inconsistent, since on the mcan I can read out the same (negative) values without any problem ...

It's not whether it's negative, it's how the bytes are padded in the ASN.1 negative integer representation. It depends, I guess 🤷 

> Well, I don't think I'd be able to successfully integrate a new asn1 parser, especially if I look at the source code of the snmpget package you linked above :-)

I'm not asking you to write a new parser, nor I'd suggest you to look at the netsnnmp package. One only has one life to live :-) Optionally integrating "rasn1" should be easier, though. But I understand it's not everyone's cup of tea.

I'll link this issue in the caveats section of the README though. Thanks for at least bothering to report it!

**Comment by HoneyryderChuck** [comment] 2021-05-20 20:17
done with a4fad8156e09c83832bc404745c3ea0727b52522
